import type { Metadata } from "next";
import '../styles/main.scss'
import Sidebar from "@/components/Sidebar/Sidebar";
import Navbar from "@/components/Navbar/Navbar";
import { Providers } from "@/store/provider";
import { Toaster } from "sonner";
import { ModalManager } from "@/modals/ModalManager";
import MainLayout from "@/components/Layout/MainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MainLayout>
            <Navbar />
            <ModalManager />
            <Toaster position="top-right" richColors />
            {children}
          </MainLayout>
        </Providers>
      </body>
    </html>
  );
}
